theme = "nightfox"

[editor]
line-number = "relative"
mouse = false
scrolloff = 20
rulers=[80,120]
shell = ["bash", "-c"]
true-color = true
bufferline = "always"

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false

[editor.search]
smart-case = false

[editor.indent-guides]
render = true
character = "╎" # Some characters that work well: "▏", "┆", "┊", "⸽"
skip-levels = 1

# [editor.whitespace]
# render = "all"

[keys.normal]
C-p = ["move_line_up","scroll_up"]
C-n = ["move_line_down","scroll_down"]
esc = ["collapse_selection","keep_primary_selection"]
C-x = ["extend_line_below", "trim_selections", "change_selection"]
C-s = ":w" 

[keys.insert]
C-space = "completion"
# [editor.whitespace.characters]
# space = "·"
# nbsp = "⍽"
# tab = ">"
# newline = "⏎"
# tabpad = "→"